# -*- coding: utf-8 -*-
"""webscraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FObvBLXP81v4iO1zlNt6qaRVfic8lkgc

**SCRAPING WISDOM PET MEDICINE WEBSITE**
"""

# Commented out IPython magic to ensure Python compatibility.
#install requests package
# %pip install requests

"""Imports run first"""

#import requests packagge
import requests

"""How to use the get method

---
"""

#scrape data from wisdom pet medicine website
requests.get("https://wisdompetmed.com/")

#scrape data form wisdom pet medicine website and save response to variable
response = requests.get("https://wisdompetmed.com/")

"""How to retrieve web page information

---


"""

#retrieve url of wisdom pet medicine website
response.url

#retrieve status code of website
response.status_code

"""STATUS CODES

*   100-199 : Informational Codes
*   200-299 : Successful Codes
*   300-399 : Redirection Codes
*   400-499 : client error codes
*   500-599 : Server Error Codes
"""

#retrieve headers of website
response.headers

"""**How to retrieve HTML Code**
---


"""

#retrieve contrent of website
response.content

#retrieve text of website
response.text

"""**How to use BeautifulSoup**

---


"""

# Commented out IPython magic to ensure Python compatibility.
#install Beautiful Soup Package
# %pip install bs4

#import Beautiful Soup package
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.text)

#prettify the html code
print(soup.prettify())

"""Using find() and find_all() commands"""

#find where the first title tag occurs in the code
soup.find("title")

#find all times article tag occurs in code for services list
soup.find_all("article")

#find business phone number
print(soup.find("span", class_="phone").text)

"""Loop find_all() methods"""

#find all featured testimonials
featured_testimonial = soup.find_all("div", class_="quote")
for testimonial in featured_testimonial:
  print(testimonial.text)

#find all staff members
staff = soup.find_all("div", class_="info col-xs-8 col-xs-offset-2 col-sm-7 col-sm-offset-0 col-md-6 col-lg-8")
for s in staff:
  print(s.text)

"""How to retrieve web page links"""

links = soup.find_all("a")
for link in links:
  print(link.text , link.get('href'))

"""How to write HTML code to a text file"""

with open("wisdom_vet.txt", "w") as f:
  f.write(soup.prettify())